### ISSUE TITLE
Administration: Problem 1

### ISSUE THREAD

**Issue by saitarunreddy** [KamandPrompt/sysadmin-test#4]
Do we in future use the stored data in its raw form(passwords)? In the question it is only specified about storage and update of the data, there is no specific information about using that data as it is in future?

**Comment by sahilarora535** [comment]
>  It has to be on your hard-drive so that you can read from it whenever you want. 

This line was added to the [problem statement](https://github.com/KamandPrompt/sysadmin-test/blob/master/Problemset/Administration.md) some days ago. You need to be able to read the contents of the file whenever you wish to (otherwise what is the use of storing passwords if you can't use them again?). Hope that solves the query.
